---
- name: Install VirtualBox dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates

- name: Add VirtualBox apt key
  apt_key:
    url: 'https://www.virtualbox.org/download/oracle_vbox_2016.asc'

- name: Add VirtualBox apt repo
  apt_repository:
    repo: 'deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib'

- name: Install VirtualBox apt package
  apt:
    name: 'virtualbox-{{ virtualbox_version }}'
    update_cache: yes
