---
- name: Add EPEL repository
  yum:
    name: epel-release
  when: ansible_distribution == 'CentOS' or
        ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install Fedora VirtualBox dependencies
  dnf:
    name:
      - qt5-qtx11extras
      - libxkbcommon
  when: ansible_distribution == 'Fedora'

- name: Install VirtualBox dependencies
  yum:
    name:
      - binutils
      - gcc
      - make
      - patch
      - libgomp
      - glibc-headers
      - glibc-devel
      - kernel-headers
      - kernel-devel
      - dkms

- name: Add Fedora VirtualBox repository
  yum_repository:
    name: virtualbox
    description: Fedora $releasever - $basearch - VirtualBox
    file: virtualbox
    enabled: yes
    baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch
    gpgcheck: yes
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
  register: virtualbox_fedora_yum_repository_result
  when: ansible_distribution == 'Fedora'

- name: Add EL VirtualBox repository
  yum_repository:
    name: virtualbox
    description: Oracle Linux / RHEL / CentOS-$releasever / $basearch - VirtualBox
    file: virtualbox
    enabled: yes
    baseurl: http://download.virtualbox.org/virtualbox/rpm/el/$releasever/$basearch
    gpgcheck: yes
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
  register: virtualbox_el_yum_repository_result
  when: ansible_distribution == 'CentOS' or
        ansible_distribution == 'Red Hat Enterprise Linux'

# This is because of a quirk in CentOS/RHEL 7 that prevents the package from installing otherwise.
- name: Update yum cache
  command: yum makecache -y
  args:
    warn: no
  changed_when: no
  when: virtualbox_fedora_yum_repository_result is changed or
        virtualbox_el_yum_repository_result is changed

- name: Install VirtualBox
  yum:
    name: 'VirtualBox-{{ virtualbox_version }}'
